http:
  port: "8888"
  basepath: "/"
  timeout:
    connection: "12000"
    read: "12000"
    
sfdcProd:
  username: "sfdcpanther@salesforce.com"
  password: "Testing@18#&^$*#"
  token: "xHkhkjHDKJHdjDHEz22JDj"
  
sfdcSandbox:
  username: "sfdcpanther@salesforce.com"
  password: "Testing@18#&^$*#"
  token: "xHkhkjHDKJHdjDHEz22JDj"