http:
  host: "localhost"
  port: "8089"
  
sfdc:
  username: "amit.singh@b2b.com"
  loginUrl: "https://login.salesforce.com/services/Soap/u/46.0"
  stoken: "wH59H7cCPJn4zZghEVN7cVfT"
  password: "wH59H7cCPJn4zZghEVN7cVfT"
  
twillio:
  username: "YOUR_CLIENT_ID"
  password: "YOUR_SSID"
  ssid: "YOUR_SSID"
  path: "/2010-04-01"
  port: "443"
  scheme: "HTTP"
  from: "12565888798"
  host: "api.twilio.com"
  timeout: "10000"
  
